apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-wireguard
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-wireguard
  template:
    metadata:
      labels:
        app: node-wireguard
    spec:
      containers:
        - name: node-wireguard
          image: socket-wireguard:latest
          ports:
            - containerPort: 8000
            - containerPort: 51820
              protocol: UDP
          env:
            - name: ISKUBERNETES
              value: "false"
            - name: ADDRESS
              value: "10.0.0.0"
            - name: PORT
              value: "8000"
            - name: REDIS_URL
              value: "redis://redis:6379"
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard
            - name: redis-url
              mountPath: /etc/redis
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: wireguard-config
          hostPath:
            path: ./etc/wireguard
            type: Directory
        - name: redis-url
          configMap:
            name: redis-url-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: node-wireguard-service
  namespace: auth
spec:
  ports:
    - port: 8000
      targetPort: 8000
    - port: 51820
      targetPort: 51820
      protocol: UDP
  selector:
    app: node-wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: auth
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-url-config
  namespace: auth
data:
  redis-url: "redis://redis:6379"

