apiVersion: v1
kind: Namespace
metadata:
  name: socket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-wireguard
  namespace: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-wireguard
  template:
    metadata:
      labels:
        app: node-wireguard
    spec:
      containers:
        - name: node-wireguard
          image: socket-wireguard:latest
          ports:
            - name: http-port
              containerPort: 8000
            - name: wireguard-port
              containerPort: 51820
              protocol: UDP
          env:
            - name: ISKUBERNETES
              value: "false"
            - name: ADDRESS
              value: "10.0.0.0"
            - name: PORT
              value: "8000"
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-url-config
                  key: redis-url
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: wireguard-config
          hostPath:
            path: ./etc/wireguard
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - name: redis-port
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: node-wireguard-service
  namespace: socket
spec:
  ports:
    - name: http-port
      port: 8000
      targetPort: 8000
    - name: wireguard-port
      port: 51820
      targetPort: 51820
      protocol: UDP
  selector:
    app: node-wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: socket
spec:
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-url-config
  namespace: socket
data:
  redis-url: "redis://redis:6379"
