apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-wireguard
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-wireguard
  template:
    metadata:
      labels:
        app: socket-wireguard
    spec:
      containers:
        - name: socket-wireguard
          image: socket-wireguard:latest
          ports:
            - name: http-port
              containerPort: 8000
            - name: wireguard-port
              containerPort: 51820
              protocol: UDP
          env:
            - name: ISKUBERNETES
              value: "false"
            - name: ADDRESS
              value: "10.0.0.0"
            - name: PORT
              value: "8000"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: socket-wireguard-service
  namespace: auth
spec:
  type: LoadBalancer  # Assuming cloud provider with LoadBalancer support
  ports:
    - name: http-port
      port: 8000
      targetPort: 8000
    - name: wireguard-port
      port: 51820
      targetPort: 51820
      protocol: UDP
  selector:
    app: socket-wireguard
