version: '3.8'

services:
  socket-wireguard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socket-wireguard
    ports:
      - "51820:51820/udp" # WireGuard default UDP port
    environment:
      - ISKUBERNETES=true
      - ADDRESS=10.0.0.0
      - PORT=51820
    cap_add:
      - NET_ADMIN
    networks:
      - wg-network
    volumes:
      - ./etc/wireguard:/etc/wireguard # WireGuard config files

networks:
  wg-network:
    driver: bridge
